#datasource:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/signup?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#  username: root
#  password: JESUTOBI
#jpa:
#  hibernate.ddl-auto: update
#  generate-ddl: true
#  show-sql: true
#
